AWSTemplateFormatVersion: 2010-09-09
Description: FormaCloud ClariSpend
Parameters:
  RootAccountID:
    Description: The root account to generate cost report.
    MinLength: 1
    Type: String
  FormaCloudID:
    Description: The customer ID that syncs your account.
    MinLength: 1
    Type: String
  FormaCloudPrincipal:
    Description: The IAM Principal that has permission to your account.
    MinLength: 1
    Type: String
  FormaCloudExternalID:
    Description: The external ID that authenticates your account.
    MinLength: 1
    Type: String
  FormaCloudPingbackArn:
    Description: The custom resource to receive pingback.
    MinLength: 1
    Type: String
  FormaCloudService:
    Description: The FormaCloud service type.
    MinLength: 1
    Type: String
Resources:
  FormaCloudClariSpendRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      RoleName: FormaCloudClariSpendRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            AWS: !Ref FormaCloudPrincipal
          Action:
          - sts:AssumeRole
          Condition:
            StringEquals: 
              sts:ExternalId: !Ref FormaCloudExternalID
      Policies:
      - PolicyName: FormaCloudCloudWatchMetricReadPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - cloudwatch:Describe*
            - cloudwatch:Get*
            - cloudwatch:List*
            Resource: "*"
      - PolicyName: FormaCloudBillingReadPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - budgets:Describe*
            - budgets:View*
            - ce:Get*
            - ce:Describe*
            - ce:List*
            - cur:Describe*
            - organizations:Describe*
            - organizations:List*
            - account:GetContactInformation
            - iam:ListAccountAliases
            Resource: "*"
      - PolicyName: FormaCloudAdditionalResourceReadPolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - ec2:Describe*
            - savingsplans:Describe*
            - rds:Describe*
            - rds:List*
            - elasticache:List*
            - elasticache:Describe*
            - redshift:Describe*
            - es:Describe*
            - es:List*
            - autoscaling:Describe*
            - compute-optimizer:Get*
            Resource: "*"
  FormaCloudPingback:
    Type: Custom::FormaCloudPingback
    Version: 1.0
    Properties:
      ServiceToken: !Ref FormaCloudPingbackArn
      RootAccountID: !Ref RootAccountID
      FormaCloudID: !Ref FormaCloudID
      FormaCloudService: !Ref FormaCloudService
      RoleArn: !GetAtt  FormaCloudClariSpendRole.Arn
Outputs:
  FormaCloudClariSpendRoleArn:
    Value: !GetAtt FormaCloudClariSpendRole.Arn
    Description: FormaCloud ClariSpend Role Arn